# Page settings
baseURL = ""
relativeURLs = true
title = "Mattermost Developers"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "../docs"
pygmentsCodeFences = true
pygmentsStyle = "manni"

[params]

  # Meta
  author = ""
  description = ""
  email = ""

  [params.mailinglist]
    enable = false

  [params.notification]
    enable = false
    url = "blog/repo-split"
    text = "On September 6th the platform repository will be split. Click through for more details."

  [params.sidebar]

  [[params.sidebar.item]]
    name = "contribute"
    displayName = "Contribute"
    draft = true

  [[params.sidebar.item]]
    name = "integrate"
    displayName = "Integrate"
    draft = true

  [[params.sidebar.item]]
    name = "extend"
    displayName = "Extend"
    draft = false

  [[params.sidebar.item]]
    name = "internal"
    displayName = "Internal"
    draft = true

  # Navigation
  [params.navigation]
    brand = "Mattermost Developers"
    home = "Home"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/contribute/getting-started"
      name = "Contribute"
      weight = 1

    [[menu.postpend]]
      url = "/integrate/"
      name = "Integrate"
      weight = 2

    [[menu.postpend]]
      url = "/extend/plugins/"
      name = "Extend"
      weight = 3

    [[menu.postpend]]
      url = "/blog/"
      name = "Blog"
      weight = 4

    # Workaround to add draft status to menu items
    [[params.navigation.drafts]]
      Contribute = true
      Integrate = true
      Extend = false
      Blog = true
      Internal = false

  # Hero section
  [params.hero]
    title = "All your Mattermost development needs"
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Contribute"
    description = "Join the hunrdeds of contributors and submit code directly to the Mattermost open-source project."
    url = "contribute/getting-started"
    button = "Start Contributing"
    icon = "icon-bulb"
    img = "img_7.jpg"
    draft = true

  [[params.intro.item]]
    title = "Integrate"
    description = "Integrate with Mattermost through incoming and outgoing webhooks, slash commands, OAuth 2.0 and the REST API."
    url = "integrate"
    button = "Start Integrating"
    icon = "icon-wrench"
    img = "img_8.jpg"
    draft = true

  [[params.intro.item]]
    title = "Extend"
    description = "Extend Mattermost to fit your purpose through powerful client and server plugins, embedding or forking."
    url = "extend/plugins"
    button = "Start Extending"
    icon = "icon-rocket"
    img = "img_10.jpg"
    draft = false

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"

  # Footer section
  [params.footer]
    enable = true
    twitter = 'https://twitter.com/mattermosthq'
    facebook = 'https://www.facebook.com/MattermostHQ'
    youtube = 'https://www.youtube.com/channel/UCNR05H72hi692y01bWaFXNA'
    copyright = '&copy; Mattermost, Inc. All Rights Reserved.'
