name: github pages

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize]

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: jamessingleton/is-organization-member@v1
        with:
          organization: mattermost
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment
        if: |
          steps.is_organization_member.outputs.result == false
        run: echo User Does Not Belong to Mattermost, preview will not be generated

  deploy:
    runs-on: ubuntu-latest
    if: check-membership.steps.is_organization_member.outputs.result == true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: make dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./${{ github.actor }}
          publish_dir: ./dist/html
          publish_branch: gh-pages
          keep_files: true
          
      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            Published to [preview environment](https://mattermost.github.io/mattermost-developer-documentation/${{ github.actor }})

