name: github pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: make dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./docs
          publish_dir: ./docs
          publish_branch: hugo-gh-pages
