name: github pages

on:
  pull_request:
    types: [assigned, opened, reopened, synchronized]
  push:
    branches:
      - gh-pages-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: make dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./${{ github.actor }}
          publish_dir: ./dist/html
          publish_branch: gh-pages
          force_orphan: true
  pr_update_text:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v1.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: 'foo-\d+'
        lowercase-branch: false
        title-template: '[%branch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: true
        body-template: '[Link to docs preview](https://mattermost.github.io/mattermost-developer-documentation/${{ github.actor }})'
        replace-body: false
        body-prefix-newline-count: 2
        uppercase-body: true
